### ISSUE TITLE
Consider using `multiselect` for the `ATTRIBUTES` param

### ISSUE THREAD

**Issue by jhuleatt** [conversationai/firestore-perspective-toxicity#2]
Since the `ATTRIBUTES` param represents a finite [list](https://support.perspectiveapi.com/s/about-the-api-attributes-and-languages) of attributes, consider using a `multiselect` param type to make it easier for consumers to configure the extension.

[Example in the `storage-resize-images` extension](https://github.com/firebase/extensions/blob/c2f3f0f15d071042e8df4901c19dcc53f32d728c/storage-resize-images/extension.yaml#L213-L231), docs under `type` [here](https://firebase.google.com/docs/extensions/alpha/parameters#options-field).

One possible issue, though, is that since there are >10 attribute types, the multiselect may become very large.

**Comment by reemaka** [comment]
Thanks for the suggestion! We did consider using multiselect but decided against it because as you mentioned the list is pretty large and also because it would be more upkeep to update this if/when we release new attributes.

**Comment by reemaka** [comment]
Also having the user look at the list on our developer site to decide which to pick means they're more likely to have read a description of the attributes.

**Comment by jhuleatt** [comment]
I see, thanks for the explanation :)
